openapi: 3.0.0
servers:
- url: '{endpoint}'
  variables:
    endpoint:
      default: ''
      description: The service endpoint, e.g. value of the client `endpoint` parameter.
info:
  title: Attestation Client
  description: Describes the interface for the per-tenant enclave service.
  contact:
    name: StackQL Studios
    url: https://stackql.io/
    email: info@stackql.io
  version: 2025-06-01-stackql-generated
  x-serviceAlias: security_attestation
  x-sdkPackage: azure-security-attestation
  x-plane: data
security:
- azure_auth:
  - user_impersonation
components:
  securitySchemes:
    azure_auth:
      description: Azure Active Directory OAuth2 Flow.
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/authorize
          scopes:
            user_impersonation: impersonate your user account
  schemas:
    AttestationResponse:
      type: object
      description: The result of an attestation operation.
      properties:
        token:
          type: string
          description: An RFC 7519 JSON Web Token, the body of which is an AttestationResult object.
    SealedAttestationResponse:
      type: object
      description: The sealed result of an attestation operation.
      properties:
        token:
          type: string
          description: Sealed RFC 7519 JSON Web Token with AttestationResult body.
    TpmAttestationResponse:
      type: object
      description: Attestation response for Trusted Platform Module (TPM) attestation.
      properties:
        data:
          type: string
          format: byte
          description: Protocol data containing attestation service response.
    OpenIDConfigurationResponse:
      type: object
      description: The response to the OpenID metadata description document API.
      properties:
        response_types_supported:
          type: array
          items:
            type: string
          description: Types supported in the OpenID metadata API.
        id_token_signing_alg_values_supported:
          type: array
          items:
            type: string
          description: List of the supported signing algorithms.
        revocation_endpoint:
          type: string
          description: Revocation endpoint.
        issuer:
          type: string
          description: Issuer tenant base endpoint.
        jwks_uri:
          type: string
          description: The URI to retrieve the signing keys.
        claims_supported:
          type: array
          items:
            type: string
          description: Set of claims supported by the OpenID metadata endpoint.
    PolicyCertificatesResponse:
      type: object
      description: The response to an attestation policy management API.
      properties:
        token:
          type: string
          description: RFC7519 JSON Web Token containing PolicyCertificatesResults object.
    PolicyCertificatesModifyResponse:
      type: object
      description: The response to an attestation policy management API.
      properties:
        token:
          type: string
          description: RFC7519 JSON Web Token with PolicyCertificatesModificationResult body.
    PolicyResponse:
      type: object
      description: The response to an attestation policy operation.
      properties:
        token:
          type: string
          description: An RFC7519 JSON Web Token structure whose body is an PolicyResult object.
    JsonWebKey:
      type: object
      description: JsonWebKey.
      properties:
        alg:
          type: string
          description: Algorithm parameter for the key.
        crv:
          type: string
          description: Curve parameter identifies the curve type.
        d:
          type: string
          description: RSA private exponent or ECC private key.
        dp:
          type: string
          description: RSA Private Key Parameter.
        dq:
          type: string
          description: RSA Private Key Parameter.
        e:
          type: string
          description: RSA public exponent, in Base64.
        k:
          type: string
          description: Symmetric key.
        kid:
          type: string
          description: Key ID parameter used to match a specific key.
        kty:
          type: string
          description: Key type parameter identifies the cryptographic algorithm family.
        'n':
          type: string
          description: RSA modulus, in Base64.
        p:
          type: string
          description: RSA secret prime.
        q:
          type: string
          description: RSA secret prime, with p < q.
        qi:
          type: string
          description: RSA Private Key Parameter.
        use:
          type: string
          description: Public key use parameter.
        x:
          type: string
          description: X coordinate for the Elliptic Curve point.
        x5c:
          type: array
          items:
            type: string
          description: X.509 certificate chain parameter.
        'y':
          type: string
          description: Y coordinate for the Elliptic Curve point.
      required:
      - kty
    JsonWebKeySet:
      type: object
      description: JsonWebKeySet.
      properties:
        keys:
          type: array
          items:
            $ref: '#/components/schemas/JsonWebKey'
          description: Array of JWK values.
    TcbBaseline:
      type: object
      description: TEE specific Tcb baseline used in attestation.
      properties:
        tcbIdentifier:
          type: string
          description: The Tcb baseline Identifier used in attestation policy.
        tcbEvaluationDataNumber:
          type: integer
          description: Monotonically increasing sequence number.
        tcbReleaseDate:
          type: string
          format: date-time
          description: Date and time when the Tcb is released.
        minimumPswLinuxVersion:
          type: string
          description: Minimum Linux PSW version required.
        minimumPswWindowsVersion:
          type: string
          description: Minimum Windows PSW version required.
        isSelectedTcb:
          type: boolean
          description: Whether this Tcb baseline is used in attestation.
    TcbBaselineResult:
      type: object
      description: Azure supported baseline details for a TEE type.
      properties:
        tcbBaselines:
          type: array
          items:
            $ref: '#/components/schemas/TcbBaseline'
          description: List of Azure supported baseline details for the TEE type.
paths:
  /attest/OpenEnclave?api-version=2025-06-01:
    post:
      operationId: Attestation_attest_open_enclave
      description: Attest to an SGX enclave. Processes an OpenEnclave report , producing an artifact. The type of
        artifact produced is dependent upon attestation policy.
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttestationResponse'
      x-stackql-resource: attestation
      x-stackql-method: attest_open_enclave
      x-stackql-verb: EXEC
  /attest/SgxEnclave?api-version=2025-06-01:
    post:
      operationId: Attestation_attest_sgx_enclave
      description: Attest to an SGX enclave. Processes an SGX enclave quote, producing an artifact. The type of
        artifact produced is dependent upon attestation policy.
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttestationResponse'
      x-stackql-resource: attestation
      x-stackql-method: attest_sgx_enclave
      x-stackql-verb: EXEC
  /attest/AzureGuest?api-version=2025-06-01:
    post:
      operationId: Attestation_attest_azure_guest
      description: Attest to an Azure Guest VM. Processes an Azure Guest TCG Log, producing an artifact. The type
        of artifact produced is dependent upon attestation policy.
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SealedAttestationResponse'
      x-stackql-resource: attestation
      x-stackql-method: attest_azure_guest
      x-stackql-verb: EXEC
  /attest/Tpm?api-version=2025-06-01:
    post:
      operationId: Attestation_attest_tpm
      description: Attest a Virtualization-based Security (VBS) enclave. Processes attestation evidence from a VBS
        enclave, producing an attestation result. The attestation result produced is dependent upon the attestation
        policy.
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TpmAttestationResponse'
      x-stackql-resource: attestation
      x-stackql-method: attest_tpm
      x-stackql-verb: EXEC
  /attest/SevSnpVm?api-version=2025-06-01:
    post:
      operationId: Attestation_attest_sev_snp_vm
      description: Attest to an SEV SNP Virtual Machine. Processes a SEV SNP Boot chain. The type of artifact produced
        is dependent upon attestation policy.
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttestationResponse'
      x-stackql-resource: attestation
      x-stackql-method: attest_sev_snp_vm
      x-stackql-verb: EXEC
  /attest/TdxVm?api-version=2025-06-01:
    post:
      operationId: Attestation_attest_tdx_vm
      description: Attest to a TDX Virtual Machine. Processes an TDX quote, producing an artifact. The type of artifact
        produced is dependent upon attestation policy.
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AttestationResponse'
      x-stackql-resource: attestation
      x-stackql-method: attest_tdx_vm
      x-stackql-verb: EXEC
  /.well-known/openid-configuration?api-version=2025-06-01:
    get:
      operationId: MetadataConfiguration_get
      description: Retrieves the OpenID Configuration data for the Azure Attestation Service. Retrieves metadata
        about the attestation signing keys in use by the attestation service.
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenIDConfigurationResponse'
      x-stackql-resource: metadata_configuration
      x-stackql-method: get
      x-stackql-verb: SELECT
  /certificates?api-version=2025-06-01:
    get:
      operationId: PolicyCertificates_get
      description: Retrieves the set of certificates used to express policy for the current tenant. Retrieves the
        set of certificates used to express policy for the current tenant.
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyCertificatesResponse'
      x-stackql-resource: policy_certificates
      x-stackql-method: get
      x-stackql-verb: SELECT
  /certificates:add?api-version=2025-06-01:
    post:
      operationId: PolicyCertificates_add
      description: Adds a new attestation policy certificate to the set of policy management certificates. Adds
        a new attestation policy certificate to the set of policy management certificates.
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyCertificatesModifyResponse'
      x-stackql-resource: policy_certificates
      x-stackql-method: add
      x-stackql-verb: EXEC
  /certificates:remove?api-version=2025-06-01:
    post:
      operationId: PolicyCertificates_remove
      description: Removes the specified policy management certificate. Note that the final policy management certificate
        cannot be removed. Removes the specified policy management certificate. Note that the final policy management
        certificate cannot be removed.
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyCertificatesModifyResponse'
      x-stackql-resource: policy_certificates
      x-stackql-method: remove
      x-stackql-verb: EXEC
  /policies/{attestation_type}?api-version=2025-06-01:
    get:
      operationId: Policy_get
      description: Retrieves the current policy for an attestation type. Retrieves the current policy for an attestation
        type.
      parameters:
      - name: attestation_type
        in: path
        required: true
        schema:
          type: string
        description: 'Specifies the trusted execution environment to be used to validate the evidence. Known values
          are: "SgxEnclave", "OpenEnclave", "AzureGuest", "SevSnpVm", "Tpm", and "TdxVm". Required.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyResponse'
      x-stackql-resource: policy
      x-stackql-method: get
      x-stackql-verb: SELECT
    put:
      operationId: Policy_set
      description: Sets the policy for a given attestation type. Sets the policy for a given attestation type.
      parameters:
      - name: attestation_type
        in: path
        required: true
        schema:
          type: string
        description: 'Specifies the trusted execution environment to be used to validate the evidence. Known values
          are: "SgxEnclave", "OpenEnclave", "AzureGuest", "SevSnpVm", "Tpm", and "TdxVm". Required.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyResponse'
      x-stackql-resource: policy
      x-stackql-method: set
      x-stackql-verb: EXEC
  /policies/{attestation_type}:reset?api-version=2025-06-01:
    post:
      operationId: Policy_reset
      description: Resets the attestation policy for the specified tenant and reverts to the default policy. Resets
        the attestation policy for the specified tenant and reverts to the default policy.
      parameters:
      - name: attestation_type
        in: path
        required: true
        schema:
          type: string
        description: 'Specifies the trusted execution environment to be used to validate the evidence. Known values
          are: "SgxEnclave", "OpenEnclave", "AzureGuest", "SevSnpVm", "Tpm", and "TdxVm". Required.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PolicyResponse'
      x-stackql-resource: policy
      x-stackql-method: reset
      x-stackql-verb: EXEC
  /certs?api-version=2025-06-01:
    get:
      operationId: SigningCertificates_get
      description: Retrieves the attestation signing keys in use by the attestation service. Retrieves metadata
        signing certificates in use by the attestation service.
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JsonWebKeySet'
      x-stackql-resource: signing_certificates
      x-stackql-method: get
      x-stackql-verb: SELECT
  /tcbbaselines/{attestation_type}?api-version=2025-06-01:
    get:
      operationId: TcbBaselines_get
      description: Retrieves a list of all Azure supported baseline details for the a TEE type along with an indication
        of which one is in enforced for the attestation provider. Retrieves a list of all Azure supported baseline
        details for the a TEE type along with an indication of which one is in enforced for the attestation provider.
      parameters:
      - name: attestation_type
        in: path
        required: true
        schema:
          type: string
        description: 'Specifies the trusted execution environment to be used to validate the evidence. Known values
          are: "SgxEnclave", "OpenEnclave", "AzureGuest", "SevSnpVm", "Tpm", and "TdxVm". Required.'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TcbBaselineResult'
      x-stackql-resource: tcb_baselines
      x-stackql-method: get
      x-stackql-verb: SELECT
